In [1]:
# Import dependencies

import random
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import requests
import traceback

In [2]:
weatherdb = "WeatherPy_challenge.csv"

In [3]:
weather_df = pd.read_csv(weatherdb)
weather_df

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain Inches (last 3 hrs),Snow Inches (last 3 hrs)
0,0,Lagoa,PT,2020-04-19 18:53:32,39.05,-27.98,57.97,66,14,28.30,few clouds,0.00,0.00
1,1,Kapaa,US,2020-04-19 18:52:34,22.08,-159.32,78.01,83,75,5.82,broken clouds,0.00,0.00
2,2,Cayenne,GF,2020-04-19 18:56:15,4.93,-52.33,84.20,79,97,11.41,moderate rain,4.38,0.00
3,3,Vestmannaeyjar,IS,2020-04-19 18:53:16,63.44,-20.27,44.60,100,90,26.40,moderate rain,0.00,0.00
4,4,Richards Bay,ZA,2020-04-19 19:00:44,-28.78,32.04,71.04,80,0,12.21,clear sky,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,562,Cajati,BR,2020-04-19 19:04:14,-24.74,-48.12,75.07,65,58,3.94,light rain,0.51,0.00
563,563,Meulaboh,ID,2020-04-19 19:03:50,4.14,96.13,80.02,82,90,3.65,light rain,1.55,0.00
564,564,Chicama,PE,2020-04-19 18:58:53,-7.84,-79.15,71.60,78,22,13.87,few clouds,0.00,0.00
565,565,Palana,RU,2020-04-19 19:08:19,59.12,159.97,9.68,95,91,4.52,light snow,0.00,0.14
566,566,Turukhansk,RU,2020-04-19 19:08:20,65.82,87.98,37.99,75,100,15.46,overcast clouds,0.00,0.00

In [4]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
rain_q = str(input("Do you want it to be raining? (yes/no) "))
snow_q = str(input("Do you want it to be snowing? (yes/no) "))

What is the minimum temperature you would like for your trip? 50
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no) no
Do you want it to be snowing? (yes/no) no

In [5]:
if rain_q == "no" and snow_q == "no":
    preferred_cities_df = weather_df.loc[(weather_df["Max Temp"] <= max_temp) & \
                                           (weather_df["Max Temp"] >= min_temp) & \
                                           (weather_df["Rain Inches (last 3 hrs)"] == 0) & \
                                           (weather_df["Snow Inches (last 3 hrs)"] == 0)]
elif rain_q == "yes" and snow_q == "no":
    preferred_cities_df = weather_df.loc[(weather_df["Max Temp"] <= max_temp) & \
                                   (weather_df["Max Temp"] >= min_temp) & \
                                   (weather_df["Rain Inches (last 3 hrs)"] != 0) & \
                                   (weather_df["Snow Inches (last 3 hrs)"] == 0)]
elif rain_q == "no" and snow_q == "yes":
    preferred_cities_df = weather_df.loc[(weather_df["Max Temp"] <= max_temp) & \
                                   (weather_df["Max Temp"] >= min_temp) & \
                                   (weather_df["Rain Inches (last 3 hrs)"] == 0) & \
                                   (weather_df["Snow Inches (last 3 hrs)"] != 0)]
else:
    print("No cities")

In [6]:
preferred_cities_df

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain Inches (last 3 hrs),Snow Inches (last 3 hrs)
0,0,Lagoa,PT,2020-04-19 18:53:32,39.05,-27.98,57.97,66,14,28.30,few clouds,0.0,0.0
1,1,Kapaa,US,2020-04-19 18:52:34,22.08,-159.32,78.01,83,75,5.82,broken clouds,0.0,0.0
4,4,Richards Bay,ZA,2020-04-19 19:00:44,-28.78,32.04,71.04,80,0,12.21,clear sky,0.0,0.0
5,5,Pahrump,US,2020-04-19 18:56:37,36.21,-115.98,63.99,34,27,7.74,scattered clouds,0.0,0.0
7,7,Chuy,UY,2020-04-19 18:51:04,-33.70,-53.46,72.50,63,0,8.70,clear sky,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,557,Locri,IT,2020-04-19 19:08:14,38.24,16.26,62.01,25,52,6.69,broken clouds,0.0,0.0
559,559,Aksay,RU,2020-04-19 19:08:15,47.26,39.87,54.00,34,99,4.47,overcast clouds,0.0,0.0
560,560,Bilma,NE,2020-04-19 19:08:16,18.69,12.92,90.00,10,9,3.53,clear sky,0.0,0.0
561,561,Presidencia Roque Saenz Pena,AR,2020-04-19 19:08:07,-26.79,-60.44,87.55,25,0,4.27,clear sky,0.0,0.0
564,564,Chicama,PE,2020-04-19 18:58:53,-7.84,-79.15,71.60,78,22,13.87,few clouds,0.0,0.0

In [7]:
# hotel dataframe
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Lagoa,PT,57.97,few clouds,39.05,-27.98,
1,Kapaa,US,78.01,broken clouds,22.08,-159.32,
4,Richards Bay,ZA,71.04,clear sky,-28.78,32.04,
5,Pahrump,US,63.99,scattered clouds,36.21,-115.98,
7,Chuy,UY,72.50,clear sky,-33.70,-53.46,
...,...,...,...,...,...,...,...
557,Locri,IT,62.01,broken clouds,38.24,16.26,
559,Aksay,RU,54.00,overcast clouds,47.26,39.87,
560,Bilma,NE,90.00,clear sky,18.69,12.92,
561,Presidencia Roque Saenz Pena,AR,87.55,clear sky,-26.79,-60.44,
564,Chicama,PE,71.60,few clouds,-7.84,-79.15,

In [8]:
import gmaps
from config import g_key

In [9]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [10]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key}

In [11]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels['results'][0]['name']
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [12]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Lagoa,PT,57.97,few clouds,39.05,-27.98,Casa Das Faias
1,Kapaa,US,78.01,broken clouds,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
4,Richards Bay,ZA,71.04,clear sky,-28.78,32.04,BON Hotel Waterfront Richards Bay
5,Pahrump,US,63.99,scattered clouds,36.21,-115.98,Best Western Pahrump Oasis
7,Chuy,UY,72.50,clear sky,-33.70,-53.46,Nuevo Hotel Plaza
...,...,...,...,...,...,...,...
557,Locri,IT,62.01,broken clouds,38.24,16.26,Grand Hotel President
559,Aksay,RU,54.00,overcast clouds,47.26,39.87,Chernaya Zhemchuzhina
560,Bilma,NE,90.00,clear sky,18.69,12.92,Expeditions TÃ©nÃ©re voyages
561,Presidencia Roque Saenz Pena,AR,87.55,clear sky,-26.79,-60.44,Hotel Aconcagua
564,Chicama,PE,71.60,few clouds,-7.84,-79.15,Hospedaje Punta Cana PERU

#### Add Marker Layer Map

In [13]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations)

fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

#### Add pop-up marker for each city

In [14]:
# Pop-Up Marker

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# Save the new dataframe as a CSV file to be used for Part 2
hotel_df.to_csv('WeatherPy_vacation.csv')